import express, { Request, Response, NextFunction } from 'express';
import crypto from 'crypto';
import cookieParser from 'cookie-parser';
import * as XLSX from 'xlsx';
import { AcademyDB } from './db';
import { hashPassword, verifyPassword, generateToken, requireAuth, setSession, clearSession, checkLoginRateLimit, recordFailedLogin, resetLoginAttempts, getAuthenticatedUser } from './auth';
import { getSupabase, isSupabaseConfigured } from './supabase';
import { isGoogleConfigured, syncEntityToGoogleSheet, uploadBackupToGoogleDrive } from './google';

export const app = express();
app.disable('x-powered-by');
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
app.use(cookieParser());
app.use((_req, res, next) => { res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('X-Frame-Options','DENY'); res.setHeader('Referrer-Policy','strict-origin-when-cross-origin'); res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()'); res.setHeader('Cross-Origin-Resource-Policy','same-origin'); next(); });

const asyncRoute = (fn: (req: Request, res: Response) => Promise<any>) => (req: Request, res: Response, next: NextFunction) => Promise.resolve(fn(req,res)).catch(next);
const userId = (req: Request) => (req as any).user?.userId as string | undefined;
const isUuid = (value: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const log = (req: Request, action: string, entityType: string, description: string, entityId?: string, status: 'SUCCESS'|'FAILED'|'PENDING' = 'SUCCESS') => AcademyDB.activity({ action, entityType, description, entityId, status, userId: userId(req) });

app.get('/api/health', (_req,res) => res.json({ ok: true }));
app.get('/api/supabase/status', asyncRoute(async (_req,res) => { if (!isSupabaseConfigured()) return res.status(503).json({ok:false,connected:false,configured:false,error:'Supabase server credentials are not configured'}); const s=getSupabase(); if(!s) return res.status(503).json({ok:false,connected:false,configured:true,error:'Supabase client could not be initialized'}); const {error}=await s.from('users').select('id',{count:'exact',head:true}); if(error) return res.status(503).json({ok:false,connected:false,configured:true,error:error.message}); return res.json({ok:true,connected:true,configured:true}); }));
app.get('/api/diagnostics', requireAuth, asyncRoute(async (_req,res)=>{ const s=getSupabase(); let dbOk=false; let error=''; if(s){const r=await s.from('users').select('id',{count:'exact',head:true}); dbOk=!r.error; error=r.error?.message||'';} res.json({status:'healthy',supabase:{configured:isSupabaseConfigured(),connected:dbOk,error},google:{configured:isGoogleConfigured()}}); }));

app.post('/api/auth/login', asyncRoute(async (req,res)=>{ const username=String(req.body?.username||'').trim(); const password=String(req.body?.password||''); if(!username||!password) return res.status(400).json({error:'يرجى إدخال اسم المستخدم وكلمة المرور'}); const limit=checkLoginRateLimit(username); if(!limit.allowed) return res.status(429).json({error:`تم إيقاف تسجيل الدخول مؤقتاً. حاول بعد ${limit.remainingMinutes} دقيقة.`}); const user=await AcademyDB.getUser(username); if(!user || !verifyPassword(password,user.password,user.password_hash)) { const failed=recordFailedLogin(username); await log(req,'محاولة دخول فاشلة','Auth',`محاولة دخول فاشلة للمستخدم ${username}`,undefined,'FAILED'); return res.status(failed.locked?429:401).json({error:failed.locked?'تم تجاوز 5 محاولات. حاول بعد 15 دقيقة.':'بيانات تسجيل الدخول غير صحيحة'}); } resetLoginAttempts(username); if (user.password && !user.password_hash) { await AcademyDB.updateUser(user.id, { password_hash: hashPassword(password), password: null }); }
 const admin={id:user.id,username:user.username,name:user.username,email:'',role:user.role} as any; const token=generateToken(admin); setSession(res,token); await log(req,'تسجيل دخول ناجح','Auth',`تم تسجيل دخول المستخدم ${user.username}`,user.id); res.json({authenticated:true,admin}); }));
app.post('/api/auth/logout',(req,res)=>{clearSession(res);res.json({success:true});});
app.get('/api/auth/me', requireAuth, asyncRoute(async (req,res)=>{ const u=await getAuthenticatedUser(userId(req)!); if(!u) return res.status(401).json({error:'المستخدم غير موجود'}); res.json(u); }));
app.put('/api/auth/profile', requireAuth, asyncRoute(async(req,res)=>{ const data=await AcademyDB.updateUser(userId(req)!,{username:String(req.body.username||'').trim()}); await log(req,'تحديث الملف الشخصي','User','تم تحديث بيانات المستخدم',data.id); res.json({...data,name:data.username,email:''}); }));
app.put('/api/auth/password', requireAuth, asyncRoute(async(req,res)=>{ const u=await AcademyDB.getUserById(userId(req)!); if(!u) return res.status(404).json({error:'المستخدم غير موجود'}); const full=await AcademyDB.getUser(u.username); if(!full||!verifyPassword(String(req.body.currentPassword||''),full.password,full.password_hash)) return res.status(400).json({error:'كلمة المرور الحالية غير صحيحة'}); const next=String(req.body.newPassword||''); if(next.length<8) return res.status(400).json({error:'كلمة المرور الجديدة يجب ألا تقل عن 8 أحرف'}); await AcademyDB.updateUser(u.id,{password_hash:hashPassword(next),password:null,must_change_password:0}); await log(req,'تغيير كلمة المرور','User','تم تغيير كلمة المرور',u.id); res.json({success:true,message:'تم تغيير كلمة المرور بنجاح'}); }));

app.get('/api/dashboard/stats',requireAuth,asyncRoute(async(_req,res)=>res.json(await AcademyDB.dashboard())));
app.get('/api/players',requireAuth,asyncRoute(async(req,res)=>res.json((await AcademyDB.players(req.query as any)).data)));
app.get('/api/players/:id',requireAuth,asyncRoute(async(req,res)=>{if(!isUuid(req.params.id)) return res.status(400).json({error:'معرّف اللاعب غير صالح'}); const p=await AcademyDB.player(req.params.id);if(!p)return res.status(404).json({error:'اللاعب غير موجود'});res.json(p);}));
app.post('/api/players',requireAuth,asyncRoute(async(req,res)=>{const p=await AcademyDB.createPlayer(req.body);await log(req,'إضافة لاعب','Player',`تمت إضافة اللاعب ${p.fullName}`,p.id);res.status(201).json(p);}));
app.put('/api/players/:id',requireAuth,asyncRoute(async(req,res)=>{if(!isUuid(req.params.id)) return res.status(400).json({error:'معرّف اللاعب غير صالح'}); const p=await AcademyDB.updatePlayer(req.params.id,req.body);await log(req,'تعديل لاعب','Player',`تم تعديل اللاعب ${p.fullName}`,p.id);res.json(p);}));
app.delete('/api/players/:id',requireAuth,asyncRoute(async(req,res)=>{if(!isUuid(req.params.id)) return res.status(400).json({error:'معرّف اللاعب غير صالح'}); await AcademyDB.deletePlayer(req.params.id);await log(req,'حذف لاعب','Player',`تم حذف اللاعب`,req.params.id);res.json({success:true,message:'تم حذف اللاعب'});}));

app.get('/api/attendance',requireAuth,asyncRoute(async(req,res)=>res.json(await AcademyDB.attendance(req.query))));
app.post('/api/attendance/batch',requireAuth,asyncRoute(async(req,res)=>{const r=await AcademyDB.batchAttendance(String(req.body.group),String(req.body.date),req.body.records||[]);await log(req,'تسجيل حضور','Attendance',`تم تسجيل حضور ${r.count} لاعب`);res.json({success:true,...r});}));
app.get('/api/payments',requireAuth,asyncRoute(async(req,res)=>res.json(await AcademyDB.payments(req.query))));
app.post('/api/payments',requireAuth,asyncRoute(async(req,res)=>{const p=await AcademyDB.payment(req.body);await log(req,'تسجيل دفعة','Payment',`تم تسجيل دفعة بقيمة ${p.amount}`,p.id);res.status(201).json(p);}));
app.get('/api/invoices',requireAuth,asyncRoute(async(req,res)=>{const rows=await AcademyDB.payments(req.query);res.json(rows.map(p=>({id:p.id,invoiceNumber:p.receiptNumber,paymentId:p.id,playerId:p.playerId,playerName:p.playerName||'',membershipCode:p.membershipCode,amount:p.amount,paymentMethod:p.paymentMethod,date:p.paymentDate,description:'اشتراك',academyName:'IFC ACADEMY',createdAt:p.createdAt})));}));
app.get('/api/subscriptions',requireAuth,asyncRoute(async(req,res)=>res.json(await AcademyDB.subscriptions(req.query))));
app.post('/api/subscriptions',requireAuth,asyncRoute(async(req,res)=>{const s=await AcademyDB.subscription(req.body);await log(req,'إنشاء اشتراك','Subscription','تم إنشاء اشتراك',s.id);res.status(201).json(s);}));
app.post('/api/subscriptions/renew',requireAuth,asyncRoute(async(req,res)=>{const r=await AcademyDB.renewSubscription(req.body);await log(req,'تجديد اشتراك','Subscription','تم تجديد الاشتراك',r.subscription.id);res.status(201).json(r);}));

app.get('/api/coaches',requireAuth,asyncRoute(async(req,res)=>res.json(await AcademyDB.coaches(req.query))));
app.post('/api/coaches',requireAuth,asyncRoute(async(req,res)=>{const c=await AcademyDB.createCoach(req.body);await log(req,'إضافة مدرب','Coach',`تمت إضافة المدرب ${c.name}`,c.id);res.status(201).json(c);}));
app.put('/api/coaches/:id',requireAuth,asyncRoute(async(req,res)=>{const c=await AcademyDB.updateCoach(req.params.id,req.body);await log(req,'تعديل مدرب','Coach',`تم تعديل المدرب ${c.name}`,c.id);res.json(c);}));
app.delete('/api/coaches/:id',requireAuth,asyncRoute(async(req,res)=>{await AcademyDB.deleteCoach(req.params.id);await log(req,'حذف مدرب','Coach','تم حذف المدرب',req.params.id);res.json({success:true,message:'تم حذف المدرب'});}));
app.post('/api/coaches/payout',requireAuth,asyncRoute(async(req,res)=>{const t=await AcademyDB.coachPayout(req.body);await log(req,'صرف راتب مدرب','Coach',`تم صرف راتب بقيمة ${t.amount}`,req.body.coachId);res.status(201).json(t);}));

app.get('/api/financial/stats',requireAuth,asyncRoute(async(_req,res)=>res.json(await AcademyDB.financialStats())));
app.get('/api/financial/transactions',requireAuth,asyncRoute(async(req,res)=>res.json(await AcademyDB.financial(req.query))));
app.post('/api/financial/transactions',requireAuth,asyncRoute(async(req,res)=>{const t=await AcademyDB.createFinancial(req.body,userId(req));await log(req,'إضافة معاملة مالية','Financial',`تمت إضافة معاملة ${t.description}`,t.id);res.status(201).json(t);}));
app.get('/api/activity-logs',requireAuth,asyncRoute(async(req,res)=>res.json(await AcademyDB.logs(req.query))));
app.get('/api/notifications',requireAuth,asyncRoute(async(_req,res)=>res.json(await AcademyDB.notifications())));
app.get('/api/backups',requireAuth,asyncRoute(async(_req,res)=>{ const s=getSupabase(); if(!s) return res.status(503).json({error:'Supabase غير متاح'}); const {data,error}=await s.from('backups').select('*').order('created_at',{ascending:false}).limit(50); if(error) throw error; res.json((data||[]).map((r:any)=>({id:r.id,type:r.type,startedAt:r.started_at,completedAt:r.completed_at,status:r.status,filename:r.filename,googleDriveFileId:r.google_drive_file_id,fileSize:r.file_size,error:r.error,createdAt:r.created_at}))); }));
app.post('/api/backups/manual',requireAuth,asyncRoute(async(req,res)=>{ if(!isGoogleConfigured()) return res.status(503).json({error:'النسخ السحابي يحتاج إعداد Google Drive'}); const s=getSupabase(); if(!s) return res.status(503).json({error:'Supabase غير متاح'}); const started=new Date().toISOString(); const filename=`IFC-Academy-${started.replace(/[:.]/g,'-')}.xlsx`; const [players,payments,attendance,financial]=await Promise.all([AcademyDB.players({limit:5000}),AcademyDB.payments({}),AcademyDB.attendance({}),AcademyDB.financial({})]); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(players.data),'Players'); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(payments),'Payments'); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(attendance),'Attendance'); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(financial),'Financial'); const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}); const upload=await uploadBackupToGoogleDrive(buffer,filename,'Manual'); const row={id:crypto.randomUUID(),type:'manual',started_at:started,completed_at:new Date().toISOString(),status:upload.success?'SUCCESS':'FAILED',filename,google_drive_file_id:upload.fileId||null,file_size:`${Math.round(buffer.length/1024)} KB`,error:upload.error||null,created_at:new Date().toISOString()}; const {data,error}=await s.from('backups').insert(row).select('*').single(); if(error) throw error; if(!upload.success) return res.status(503).json({error:upload.error,backup:row}); await log(req,'نسخ احتياطي','Backup',`تم إنشاء نسخة احتياطية ${filename}`,row.id); res.json({success:true,message:'تم إنشاء النسخة الاحتياطية',backup:{id:data.id,type:data.type,startedAt:data.started_at,completedAt:data.completed_at,status:data.status,filename:data.filename,googleDriveFileId:data.google_drive_file_id,fileSize:data.file_size,error:data.error,createdAt:data.created_at}}); }));
app.post('/api/supabase/test',requireAuth,asyncRoute(async(_req,res)=>{const s=getSupabase(); if(!s)return res.status(503).json({success:false,message:'Supabase غير مُعد في Vercel'}); const {error}=await s.from('users').select('id',{count:'exact',head:true}); res.json(error?{success:false,message:error.message}:{success:true,message:'الاتصال بقاعدة Supabase ناجح'});}));
app.post('/api/supabase/config',requireAuth,asyncRoute(async(_req,res)=>res.status(400).json({success:false,message:'إعدادات Supabase تُدار فقط من Vercel Environment Variables لأسباب أمنية.'})));
app.post('/api/supabase/sync',requireAuth,asyncRoute(async(_req,res)=>res.json({success:true,message:'Supabase هو المصدر الوحيد للبيانات؛ لا توجد مزامنة من Local JSON.'})));

app.get('/api/settings',requireAuth,asyncRoute(async(_req,res)=>res.json(await AcademyDB.settings())));
app.put('/api/settings',requireAuth,asyncRoute(async(req,res)=>{const s=await AcademyDB.updateSettings(req.body);await log(req,'تحديث الإعدادات','Settings','تم تحديث إعدادات الأكاديمية');res.json(s);}));

async function exportXlsx(res: Response, name: string, sheet: string, rows: any[]) { const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),sheet);const b=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition',`attachment; filename="${name}"`);res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.send(b); }
app.get('/api/export/players',requireAuth,asyncRoute(async(_req,res)=>{const p=(await AcademyDB.players({limit:100}).then(x=>x.data));await exportXlsx(res,'IFC-Academy-Players.xlsx','Players',p);}));
app.get('/api/export/payments',requireAuth,asyncRoute(async(_req,res)=>{const p=await AcademyDB.payments({});await exportXlsx(res,'IFC-Academy-Payments.xlsx','Payments',p);}));
app.get('/api/export/attendance',requireAuth,asyncRoute(async(_req,res)=>{const p=await AcademyDB.attendance({});await exportXlsx(res,'IFC-Academy-Attendance.xlsx','Attendance',p);}));
app.get('/api/export/financial',requireAuth,asyncRoute(async(_req,res)=>{const p=await AcademyDB.financial({});await exportXlsx(res,'IFC-Academy-Financial.xlsx','Financial',p);}));
app.get('/api/export/activity-logs',requireAuth,asyncRoute(async(_req,res)=>{const p=await AcademyDB.logs({});await exportXlsx(res,'IFC-Academy-Activity-Logs.xlsx','Activity',p);}));

app.post('/api/google/sync-all',requireAuth,asyncRoute(async(_req,res)=>{if(!isGoogleConfigured())return res.status(503).json({success:false,message:'Google integration is not configured'});const [players,payments,attendance]=await Promise.all([AcademyDB.players({limit:5000}),AcademyDB.payments({}),AcademyDB.attendance({})]);const results:any={};results.players=await syncEntityToGoogleSheet('Players',Object.keys(players.data[0]||{}),players.data.map(Object.values));results.payments=await syncEntityToGoogleSheet('Payments',Object.keys(payments[0]||{}),payments.map(Object.values));results.attendance=await syncEntityToGoogleSheet('Attendance',Object.keys(attendance[0]||{}),attendance.map(Object.values));res.json({success:true,message:'تمت المزامنة',results});}));

app.use((req,res)=>res.status(404).json({error:`المسار غير موجود: ${req.method} ${req.path}`}));
app.use((err:any,_req:Request,res:Response,_next:NextFunction)=>{console.error('API error:',err?.message||err);const status=err?.code==='23505'?409:err?.status||500;res.status(status).json({error:err?.message||'حدث خطأ داخلي في الخادم'});});
