import { v4 as uuid } from 'uuid';
import { getSupabase } from './supabase';
import { Player, Subscription, Payment, AttendanceRecord, AdminUser, AcademySettings, DashboardStats, ActivityLog, AppNotification, FinancialTransaction, Coach, Invoice } from '../src/types';

function db() { const s = getSupabase(); if (!s) throw new Error('Supabase is not configured'); return s; }
function searchText(value: unknown) { return String(value ?? '').normalize('NFKC').replace(/[^\p{L}\p{N}\s@._-]/gu, '').trim().slice(0, 80); }
function age(birth?: string) { if (!birth) return 0; const d = new Date(birth); if (Number.isNaN(d.getTime())) return 0; const now = new Date(); return Math.max(0, now.getFullYear() - d.getFullYear() - ((now.getMonth() < d.getMonth() || (now.getMonth() === d.getMonth() && now.getDate() < d.getDate())) ? 1 : 0)); }
function mapPlayer(r: any): Player { return { id: r.id, membershipCode: r.code || '', nationalId: r.national_id || '', fullName: r.name || '', phone: r.phone || '', birthDate: r.birth_date || '', age: age(r.birth_date), group: r.team_group || 'ناشئين', status: r.status || 'Active', notes: r.notes || '', createdAt: r.created_at }; }
function mapPayment(r: any): Payment { return { id: r.id, playerId: r.player_id, playerName: r.player_name || '', membershipCode: r.player_code || '', subscriptionId: r.subscription_id || undefined, amount: Number(r.amount || 0), paymentMethod: r.payment_method || 'Cash', paidBy: r.paid_by, paymentDate: r.payment_date, status: 'Paid', notes: r.notes || '', receiptNumber: r.invoice_no || '', createdAt: r.created_at }; }
function mapAttendance(r: any): AttendanceRecord { return { id: r.id, playerId: r.player_id, playerName: r.player_name || '', membershipCode: r.player_code || '', group: r.team_group || 'ناشئين', date: r.attendance_date, status: r.status, notes: r.notes || '', markedAt: r.created_at }; }
function mapSub(r: any): Subscription { const end = r.end_date || ''; const days = end ? Math.ceil((new Date(end).getTime() - Date.now()) / 86400000) : undefined; let status: any = r.status || 'Unpaid'; if (days !== undefined && days < 0) status = 'Expired'; else if (days !== undefined && days <= 7) status = 'ExpiringSoon'; return { id: r.id, playerId: r.playerId || r.player_id, playerName: r.player_name || '', membershipCode: r.player_code || '', group: r.team_group, planName: r.plan_name || 'اشتراك', value: Number(r.value || 0), startDate: r.start_date || '', endDate: end, status, daysRemaining: days, lastPaymentDate: r.last_payment_date, lastPaidBy: r.last_paid_by, createdAt: r.created_at }; }
function mapCoach(r: any): Coach { return { id: r.id, name: r.name, phone: r.phone || '', assignedGroup: r.assigned_group || 'جميع المجموعات', role: r.role || 'مدرب', monthlySalary: Number(r.monthly_salary || 0), joinedDate: r.joined_date || '', status: r.status || 'Active', notes: r.notes || '', totalSalariesPaid: Number(r.total_salaries_paid || 0), lastPayoutDate: r.last_payout_date }; }

export class AcademyDB {
  static async getUser(username: string) { const { data, error } = await db().from('users').select('id,username,password,password_hash,role,must_change_password,created_at').ilike('username', username).maybeSingle(); if (error) throw error; return data; }
  static async getUserById(id: string) { const { data, error } = await db().from('users').select('id,username,role,must_change_password,created_at').eq('id', id).maybeSingle(); if (error) throw error; return data; }
  static async updateUser(id: string, patch: any) { const { data, error } = await db().from('users').update(patch).eq('id', id).select('id,username,role,must_change_password,created_at').single(); if (error) throw error; return data; }

  static async players(filter: { query?: string; group?: string; status?: string; page?: number; limit?: number } = {}) {
    const page = Math.max(1, Number(filter.page) || 1), limit = Math.min(100, Math.max(1, Number(filter.limit) || 50)); let q = db().from('players').select('*', { count: 'exact' }).order('created_at', { ascending: false }).range((page - 1) * limit, page * limit - 1);
    if (filter.group && filter.group !== 'All') q = q.eq('team_group', filter.group);
    if (filter.status && filter.status !== 'All') q = q.eq('status', filter.status);
    if (filter.query) { const s = searchText(filter.query); if (s) q = q.or(`name.ilike.%${s}%,code.ilike.%${s}%,phone.ilike.%${s}%,national_id.ilike.%${s}%`); }
    const { data, error, count } = await q; if (error) throw error; return { data: (data || []).map(mapPlayer), total: count || 0, page, limit };
  }
  static async player(id: string) { const s = db(); const { data, error } = await s.from('players').select('*').eq('id', id).maybeSingle(); if (error) throw error; if (!data) return null; const p = mapPlayer(data); const [subs, pays, att] = await Promise.all([s.from('subscriptions').select('*').eq('playerId', id).order('created_at', { ascending: false }), s.from('payments').select('*').eq('player_id', id).order('payment_date', { ascending: false }), s.from('attendance').select('*').eq('player_id', id).order('attendance_date', { ascending: false })]); return { ...p, subscriptions: (subs.data || []).map(mapSub), payments: (pays.data || []).map(mapPayment), attendance: (att.data || []).map(mapAttendance) }; }
  static async createPlayer(input: any) { const row = { id: uuid(), code: input.membershipCode || input.code, name: input.fullName || input.name, phone: input.phone || '', national_id: input.nationalId || null, birth_date: input.birthDate || null, team_group: input.group || input.team_group || 'ناشئين', membership_type: input.membershipType || 'Standard', subscription_duration: input.subscriptionDuration || null, price: Number(input.price || 0), payment_method: input.paymentMethod || null, status: input.status || 'Active', start_date: input.startDate || null, end_date: input.endDate || null }; const { data, error } = await db().from('players').insert(row).select('*').single(); if (error) throw error; return mapPlayer(data); }
  static async updatePlayer(id: string, input: any) { const row: any = {}; const m: any = { membershipCode: 'code', fullName: 'name', phone: 'phone', nationalId: 'national_id', birthDate: 'birth_date', group: 'team_group', membershipType: 'membership_type', subscriptionDuration: 'subscription_duration', price: 'price', paymentMethod: 'payment_method', status: 'status', startDate: 'start_date', endDate: 'end_date' }; for (const [k, col] of Object.entries(m) as [string, string][]) if (input[k] !== undefined) row[col] = input[k]; const { data, error } = await db().from('players').update(row).eq('id', id).select('*').single(); if (error) throw error; return mapPlayer(data); }
  static async deletePlayer(id: string) { const s = db(); const { error } = await s.from('players').delete().eq('id', id); if (error) throw error; return true; }

  static async attendance(filter: any = {}) { let q = db().from('attendance').select('*').order('attendance_date', { ascending: false }).order('created_at', { ascending: false }).limit(500); if (filter.group && filter.group !== 'All') q = q.eq('team_group', filter.group); if (filter.date) q = q.eq('attendance_date', filter.date); if (filter.playerId) q = q.eq('player_id', filter.playerId); if (filter.status && filter.status !== 'All') q = q.eq('status', filter.status); if (filter.query) { const x = searchText(filter.query); if (x) q = q.or(`player_name.ilike.%${x}%,player_code.ilike.%${x}%`); } const { data, error } = await q; if (error) throw error; return (data || []).map(mapAttendance); }
  static async batchAttendance(group: string, date: string, records: any[]) { const s = db(); const ids = records.map(r => r.playerId); if (!ids.length) return { count: 0 }; const { data: players, error: pe } = await s.from('players').select('id,code,name,team_group').in('id', ids); if (pe) throw pe; const rows = records.map(r => { const p = (players || []).find(x => x.id === r.playerId); return { id: uuid(), player_id: r.playerId, player_code: p?.code || '', player_name: p?.name || '', team_group: p?.team_group || group, status: r.status, attendance_date: date, notes: r.notes || null }; }); for (const row of rows) { const existing = await s.from('attendance').select('id').eq('player_id', row.player_id).eq('attendance_date', row.attendance_date).limit(1).maybeSingle(); if (existing.error) throw existing.error; if (existing.data?.id) { const { error } = await s.from('attendance').update({ player_code: row.player_code, player_name: row.player_name, team_group: row.team_group, status: row.status, notes: row.notes, created_at: new Date().toISOString() }).eq('id', existing.data.id); if (error) throw error; } else { const { error } = await s.from('attendance').insert(row); if (error) throw error; } } return { count: rows.length }; }

  static async payments(filter: any = {}) { let q = db().from('payments').select('*').order('payment_date', { ascending: false }).limit(500); if (filter.method && filter.method !== 'All') q = q.eq('payment_method', filter.method); if (filter.query) { const x = searchText(filter.query); if (x) q = q.or(`player_name.ilike.%${x}%,player_code.ilike.%${x}%,invoice_no.ilike.%${x}%`); } if (filter.startDate) q = q.gte('payment_date', filter.startDate); if (filter.endDate) q = q.lte('payment_date', filter.endDate); const { data, error } = await q; if (error) throw error; return (data || []).map(mapPayment); }
  static async payment(input: any) { const s = db(); const p = await this.player(input.playerId); if (!p) throw new Error('اللاعب غير موجود'); const row = { id: uuid(), invoice_no: input.invoiceNo || `INV-${Date.now()}`, player_id: input.playerId, player_name: p.fullName, player_code: p.membershipCode, amount: Number(input.amount), payment_method: input.paymentMethod, payment_date: input.paymentDate, ...(input.subscriptionId ? { subscription_id: input.subscriptionId } : {}), ...(input.paidBy ? { paid_by: input.paidBy } : {}), ...(input.notes ? { notes: input.notes } : {}) }; const { data, error } = await s.from('payments').insert(row).select('*').single(); if (error) throw error; return mapPayment(data); }

  static async subscriptions(filter: any = {}) { let q = db().from('subscriptions').select('*').order('created_at', { ascending: false }).limit(500); if (filter.query) { const x = searchText(filter.query); if (x) q = q.or(`player_name.ilike.%${x}%,player_code.ilike.%${x}%`); } if (filter.group && filter.group !== 'All') q = q.eq('team_group', filter.group); const { data, error } = await q; if (error) throw error; return (data || []).map(mapSub); }
  static async subscription(input: any) { const s = db(); const p = await this.player(input.playerId); if (!p) throw new Error('اللاعب غير موجود'); const row = { id: uuid(), playerId: input.playerId, player_name: p.fullName, player_code: p.membershipCode, team_group: p.group, plan_name: input.planName || 'اشتراك', value: Number(input.value || 0), start_date: input.startDate, end_date: input.endDate, status: 'Paid', updated_at: new Date().toISOString() }; const { data, error } = await s.from('subscriptions').insert(row).select('*').single(); if (error) throw error; return mapSub(data); }
  static async renewSubscription(input: any) { const sub = await this.subscription(input); let payment; if (input.payNow) payment = await this.payment({ playerId: input.playerId, subscriptionId: sub.id, amount: input.value, paymentMethod: input.paymentMethod || 'Cash', paidBy: input.paidBy, paymentDate: input.startDate, notes: input.notes, invoiceNo: `INV-${Date.now()}` }); return { subscription: sub, payment }; }

  static async dashboard(): Promise<DashboardStats> { const s = db(); const month = new Date(); const start = new Date(month.getFullYear(), month.getMonth(), 1).toISOString().slice(0,10); const end = new Date(month.getFullYear(), month.getMonth() + 1, 1).toISOString().slice(0,10); const today = new Date().toISOString().slice(0, 10); const [all, active, inactive, paid, att] = await Promise.all([s.from('players').select('*', { count: 'exact', head: true }), s.from('players').select('*', { count: 'exact', head: true }).eq('status', 'Active'), s.from('players').select('*', { count: 'exact', head: true }).eq('status', 'Inactive'), s.from('payments').select('amount').gte('payment_date', start).lt('payment_date', end), s.from('attendance').select('*', { count: 'exact', head: true }).eq('attendance_date', today).eq('status', 'Present')]); return { totalPlayers: all.count || 0, activePlayers: active.count || 0, inactivePlayers: inactive.count || 0, paidThisMonth: (paid.data || []).reduce((n: number, x: any) => n + Number(x.amount || 0), 0), unpaidThisMonth: 0, attendanceTodayCount: att.count || 0 }; }

  static async activity(input: Omit<ActivityLog, 'id' | 'timestamp'>) { const { error } = await db().from('activity_logs').insert({ id: uuid(), user_id: input.userId, action: input.action, entity_type: input.entityType, entity_id: input.entityId || null, description: input.description, status: input.status, timestamp: new Date().toISOString() }); if (error) console.error('activity log:', error.message); }
  static async logs(filter: any = {}) { let q = db().from('activity_logs').select('*').order('timestamp', { ascending: false }).limit(500); if (filter.entityType) q = q.eq('entity_type', filter.entityType); if (filter.action) q = q.ilike('action', `%${filter.action}%`); if (filter.query) { const x = searchText(filter.query); if (x) q = q.ilike('description', `%${x}%`); } const { data, error } = await q; if (error) throw error; return (data || []).map((r: any) => ({ id: r.id, userId: r.user_id, action: r.action, entityType: r.entity_type, entityId: r.entity_id, description: r.description, timestamp: r.timestamp, status: r.status })); }

  static async coaches(filter: any = {}) { let q = db().from('coaches').select('*').order('created_at', { ascending: false }); if (filter.group && filter.group !== 'All') q = q.eq('assigned_group', filter.group); if (filter.status && filter.status !== 'All') q = q.eq('status', filter.status); if (filter.query) { const x = searchText(filter.query); if (x) q = q.or(`name.ilike.%${x}%,phone.ilike.%${x}%`); } const { data, error } = await q; if (error) throw error; return (data || []).map(mapCoach); }
  static async createCoach(input: any) { const { data, error } = await db().from('coaches').insert({ id: uuid(), name: input.name, phone: input.phone, assigned_group: input.assignedGroup, role: input.role, monthly_salary: Number(input.monthlySalary), joined_date: input.joinedDate || new Date().toISOString().slice(0, 10), status: input.status || 'Active', notes: input.notes || null }).select('*').single(); if (error) throw error; return mapCoach(data); }
  static async updateCoach(id: string, input: any) { const row: any = {}; const m: any = { name: 'name', phone: 'phone', assignedGroup: 'assigned_group', role: 'role', monthlySalary: 'monthly_salary', joinedDate: 'joined_date', status: 'status', notes: 'notes' }; for (const [k, c] of Object.entries(m) as Array<[string, string]>) if (input[k] !== undefined) row[c] = input[k]; const { data, error } = await db().from('coaches').update(row).eq('id', id).select('*').single(); if (error) throw error; return mapCoach(data); }
  static async deleteCoach(id: string) { const { error } = await db().from('coaches').delete().eq('id', id); if (error) throw error; return true; }
  static async coachPayout(input: any) { const c = await db().from('coaches').select('*').eq('id', input.coachId).single(); if (c.error) throw c.error; const amount = Number(input.amount); const now = new Date().toISOString(); const { error: pe } = await db().from('coach_payouts').insert({ id: uuid(), coach_id: input.coachId, coach_name: c.data.name, amount, payout_date: input.payoutDate, notes: input.notes || null, payment_method: input.paymentMethod }); if (pe) throw pe; await db().from('coaches').update({ total_salaries_paid: Number(c.data.total_salaries_paid || 0) + amount, last_payout_date: input.payoutDate }).eq('id', input.coachId); const { error: fe } = await db().from('financial_transactions').insert({ id: uuid(), type: 'salary', amount, date: input.payoutDate, description: `راتب المدرب ${c.data.name}`, category: 'رواتب المدربين', coach_name: c.data.name, notes: input.notes || null, created_at: now }); if (fe) throw fe; return { id: uuid(), type: 'salary', amount, date: input.payoutDate, description: `راتب المدرب ${c.data.name}`, category: 'رواتب المدربين', coachName: c.data.name, notes: input.notes, createdAt: now } as FinancialTransaction; }

  static async financial(filter: any = {}) { let q = db().from('financial_transactions').select('*').order('date', { ascending: false }).limit(500); if (filter.type && filter.type !== 'All') q = q.eq('type', filter.type); if (filter.query) { const x = searchText(filter.query); if (x) q = q.ilike('description', `%${x}%`); } const { data, error } = await q; if (error) throw error; return (data || []).map((r: any) => ({ id: r.id, type: r.type, amount: Number(r.amount), date: r.date, description: r.description, category: r.category, coachName: r.coach_name, notes: r.notes, userId: r.user_id, createdAt: r.created_at })); }
  static async financialStats() { const rows = await this.financial(); return { totalRevenue: rows.filter(x => x.type === 'income').reduce((n, x) => n + x.amount, 0) + rows.filter(x => x.type === 'salary' ? false : false).reduce((n,x)=>n+x.amount,0) + (await this.payments()).reduce((n,x)=>n+x.amount,0), totalExpenses: rows.filter(x => x.type === 'expense').reduce((n,x)=>n+x.amount,0), totalSalaries: rows.filter(x => x.type === 'salary').reduce((n,x)=>n+x.amount,0), netBalance: (await this.payments()).reduce((n,x)=>n+x.amount,0) - rows.reduce((n,x)=>n+x.amount,0), paymentsCount: (await this.payments()).length, transactionsCount: rows.length }; }
  static async createFinancial(input: any, userId?: string) { const row = { id: uuid(), type: input.type, amount: Number(input.amount), date: input.date, description: input.description, category: input.category || null, coach_name: input.coachName || null, notes: input.notes || null, user_id: userId || null, created_at: new Date().toISOString() }; const { data, error } = await db().from('financial_transactions').insert(row).select('*').single(); if (error) throw error; return { id: data.id, type: data.type, amount: Number(data.amount), date: data.date, description: data.description, category: data.category, coachName: data.coach_name, notes: data.notes, userId: data.user_id, createdAt: data.created_at } as FinancialTransaction; }

  static async settings() { const { data, error } = await db().from('academy_settings').select('*').eq('id', 'main').maybeSingle(); if (error) throw error; return data ? { academyName: data.academy_name, phone: data.phone || '', address: data.address || '', currency: data.currency || 'EGP', defaultMonthlyFee: Number(data.default_monthly_fee || 0), adminNotifications: Boolean(data.admin_notifications) } : { academyName: 'IFC ACADEMY', phone: '', address: '', currency: 'EGP', defaultMonthlyFee: 0, adminNotifications: true }; }
  static async updateSettings(input: any) { const row = { id: 'main', academy_name: input.academyName, phone: input.phone, address: input.address, currency: input.currency, default_monthly_fee: Number(input.defaultMonthlyFee || 0), admin_notifications: Boolean(input.adminNotifications), updated_at: new Date().toISOString() }; const { data, error } = await db().from('academy_settings').upsert(row).select('*').single(); if (error) throw error; return { academyName: data.academy_name, phone: data.phone || '', address: data.address || '', currency: data.currency || 'EGP', defaultMonthlyFee: Number(data.default_monthly_fee || 0), adminNotifications: Boolean(data.admin_notifications) }; }
  static async notifications() { const { data, error } = await db().from('notifications').select('*').order('date', { ascending: false }).limit(100); if (error) throw error; return (data || []).map((r: any) => ({ id: r.id, type: r.type, title: r.title, message: r.message, playerId: r.player_id, date: r.date, read: r.read })); }
}
